seqs = {}

seqs['sv1']  = 'EKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEKEK'   # 0
seqs['sv2']  = 'EEEKKKEEEKKKEEEKKKEEEKKKEEEKKKEEEKKKEEEKKKEEEKKKEK'   # 1
seqs['sv3']  = 'KEKKKEKKEEKKEEKEKEKEKEEKKKEEKEKEKEKKKEEKEKEEKKEEEE'   # 2
seqs['sv4']  = 'KEKEKKEEKEKKEEEKKEKEKEKKKEEKKKEEKEEKKEEKKKEEKEEEKE'   # 3
seqs['sv5']  = 'KEKEEKEKKKEEEEKEKKKKEEKEKEKEKEEKKEEKKKKEEKEEKEKEKE'   # 4
seqs['sv6']  = 'EEEKKEKKEEKEEKKEKKEKEEEKKKEKEEKKEEEKKKEKEEEEKKKKEK'   # 5
seqs['sv7']  = 'EEEEKKKKEEEEKKKKEEEEKKKKEEEEKKKKEEEEKKKKEEEEKKKKEK'   # 6
seqs['sv8']  = 'KKKKEEEEKKKKEEEEKKKKEEEEKKKKEEEEKKKKEEEEKKKKEEEEKE'   # 7
seqs['sv9']  = 'EEKKEEEKEKEKEEEEEKKEKKEKKEKKKEEKEKEKKKEKKKKEKEEEKE'   # 8
seqs['sv10'] = 'EKKKKKKEEKKKEEEEEKKKEEEKKKEKKEEKEKEEKEKKEKKEEKEEEE'   # 9
seqs['sv11'] = 'EKEKKKKKEEEKKEKEEEEKEEEEKKKKKEKEEEKEEKKEEKEKKKEEKK'   # 10
seqs['sv12'] = 'EKKEEEEEEKEKKEEEEKEKEKKEKEEKEKKEKKKEKKEEEKEKKKKEKK'   # 11
seqs['sv13'] = 'KEKKKEKEKKEKKKEEEKKKEEEKEKKKEEKKEKKEKKEEEEEEEKEEKE'   # 12
seqs['sv14'] = 'EKKEKEEKEEEEKKKKKEEKEKKEKKKKEKKKKKEEEEEEKEEKEKEKEE'   # 13
seqs['sv15'] = 'KKEKKEKKKEKKEKKEEEKEKEKKEKKKKEKEKKEEEEEEEEKEEKKEEE'   # 14
seqs['sv16'] = 'EKEKEEKKKEEKKKKEKKEKEEKKEKEKEKKEEEEEEEEEKEKKEKKKKE'   # 15
seqs['sv17'] = 'EKEKKKKKKEKEKKKKEKEKKEKKEKEEEKEEKEKEKKEEKKEEEEEEEE'   # 16
seqs['sv18'] = 'KEEKKEEEEEEEKEEKKKKKEKKKEKKEEEKKKEEKKKEEEEEEKKKKEK'   # 17
seqs['sv19'] = 'EEEEEKKKKKEEEEEKKKKKEEEEEKKKKKEEEEEKKKKKEEEEEKKKKK'   # 18
seqs['sv20'] = 'EEKEEEEEEKEEEKEEKKEEEKEKKEKKEKEEKKEKKKKKKKKKKKKEEE'   # 19
seqs['sv21'] = 'EEEEEEEEEKEKKKKKEKEEKKKKKKEKKEKKKKEKKEEEEEEKEEEKKK'   # 20
seqs['sv22'] = 'KEEEEKEEKEEKKKKEKEEKEKKKKKKKKKKKKEKKEEEEEEEEKEKEEE'   # 21
seqs['sv23'] = 'EEEEEKEEEEEEEEEEEKEEKEKKKKKKEKKKKKKKEKEKKKKEKKEEKK'   # 22
seqs['sv24'] = 'EEEEKEEEEEKEEEEEEEEEEEEKKKEEKKKKKEKKKKKKKEKKKKKKKK'   # 23
seqs['sv25'] = 'EEEEEEEEEEEKEEEEKEEKEEKEKKKKKKKKKKKKKKKKKKEEKKEEKE'   # 24
seqs['sv26'] = 'KEEEEEEEKEEKEEEEEEEEEKEEEEKEEKKKKKKKKKKKKKKKKKKKKE'   # 25
seqs['sv27'] = 'KKEKKKEKKEEEEEEEEEEEEEEEEEEEEKEEKKKKKKKKKKKKKKKEKK'   # 26
seqs['sv28'] = 'EKKKKKKKKKKKKKKKKKKKKKEEEEEEEEEEEEEEEEEEKKEEEEEKEK'   # 27
seqs['sv29'] = 'KEEEEKEEEEEEEEEEEEEEEEEEEEEKKKKKKKKKKKKKKKKKKKKKKK'   # 28
seqs['sv30'] = 'EEEEEEEEEEEEEEEEEEEEEEEEEKKKKKKKKKKKKKKKKKKKKKKKKK'   # 29

# Yi-Hsuan's abnormal sequences
seqs['as1']  = 'KKKKKEKKKKKEKKKKEKKKKEKKEKEEEKEEEEKEEEEKEEEEKEEEEE'   # 30
seqs['as2']  = 'EEEEEEEEKKEKKKKEEEEEEEEEEEKKKKEEEKEKEKKKKKKKKKKKKK'   # 31
seqs['as3']  = 'KKKKEEEEEEEEEEEEEEEEEEKKEKKKKKKKKKKKKKKEKEEEEEKKKK'   # 32
seqs['as4']  = 'KKKKKKEEEEEEEEEEEEEEEKKKKKKKKKKKKKKKKKKEEEEEEEEEEK'   # 33

# kappa ~ 0.5:
seqs['ckappa1']  = 'KKKEEEEEEEEKKKKKKKKKKEEEEEEEEEEKKKKKKKKKEEKEEEKEKE' #	-2.55		0.500   # 36
seqs['ckappa2']  = 'KKKEEEEEEEKKEEEEEKKKEKKKKKKKKEEEEEEEEEEEEKKKKKKKKK' #	-4.04		0.496   # 37
seqs['ckappa3']  = 'KKKKKKKKKKKKKKKEKKKKKEKKEEEEKEEEEEKEEEEEKEEEEEEEEE' #	-19.56		0.499   # 35
seqs['ckappa4']  = 'KKKKKKKKKKEKKKKKEKKKKEKKKKEEKEEEEEKEEEEEEEEEEEEEEE' #	-19.75		0.507   # 34

# scd ~ -10:
seqs['cSCD1']  = 'KKKKEKKKKEEKKKKKKKEEKKKKKEEEEKKEEEEEEEKEEKEEEKEEEE' #	-9.94		0.209   # 38
seqs['cSCD2']  = 'KEKKKKKKKKEEKKKKKKEEKKKKKEEEEEKKEEEEEEEEKKKEEEEEEE' #	-9.95		0.340   # 39
seqs['cSCD3']  = 'EEEEEEEKKKKKKKKKKKKKKKEEEKKKKKKKKKKEEEEEEEEEEEEEEE' #	-10.03		0.726   # 41
seqs['cSCD4']  = 'EEEEEKKKKKKKKKKKKKKKKKKKKEEEEEEEEEEEEEEEEEEEEKKKKK' #	-9.75		0.798   # 40

# Hue Sun's sequences
seqs['obs1']   = 'KKKKKKKKKKEEEEEEEEEEEEKKKKKEEEEEEEEEEEEEKKKKKKKKKK'   # blocks 10-12-5-13-10
seqs['ebs1']   = 'EEEEEEEEEKKKKKKKKEEEEEEEEKKKKKKKKEEEEEEEEKKKKKKKKK'   # blocks 9-8-8-8-8-9

############ Weak polyelectrolyte sequences ############
seqs['cp1']  = 'KKKKKKKKKKKKKKKKKKKKKKKKKKKEEEEEEEEEEEEEEEEEEEEEEE' # 4 	-27.04 		0.987      # 42
seqs['cp2']  = 'KEKKEKKEEKEKEKEKKKEEKEEKEKKEEKKKEEKKKEEKKEEKEEKKEK' # 4 	0.003076	0.000934   # 43
seqs['cp3']  = 'EEEKEEEEEKEEEKKKKKEKKKKKKKKEEKKKKKKKKKKKKKKKEEKEEE' # 12 	-3.91 		0.378      # 44
seqs['cp4']  = 'KEKKEKKKEKKKKEEEKKEKKKEEKEEKKKEKEEKKKEKEKKEEKKKKEK' # 12 	5.177	 	0.00289    # 45

seqs['cn1']  = 'KKKKKKKKKKKKKKKKKKKKKKEKEEEEEEEEEEEEEEEEEEEEEEEEEE' #-4 	-26.72 		0.947      # 46
seqs['cn2']  = 'EKEEEKEEEKEKKKKEKEEEKEKKEKEEEKEKKEEKKEEKEKEKKKKEEE' #-4 	-0.325 		0.00392    # 47
seqs['cn3']  = 'KKKKKKKKKEKEEEKKKKEEEKKEEEEEEEEEEEEEEEEEEEEEKKEEKE' #-12 	-7.296 		0.467      # 48
seqs['cn4']  = 'EEEEEKKKEEEKKKEEEEKEKKEKEEKKEKKEEKEEEKKEEKEEKEEEEE' #-12 	5.201 		0.00457    # 49


seqs['E50'] = 'E'*50
seqs['K50'] = 'K'*50